version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: asistencia_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: asistencia_db
      POSTGRES_HOST_AUTH_METHOD: trust  # Temporal para inicialización
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d asistencia_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: asistencia_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: asistencia_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - asistencia_network

networks:
  asistencia_network:
    driver: bridge

volumes:
  postgres_data: