FROM postgres:13

# Solo necesitamos copiar los archivos de configuración
COPY postgresql.conf /etc/postgresql/
COPY init.sql /docker-entrypoint-initdb.d/

# Ajustar permisos
RUN chown postgres:postgres /etc/postgresql/postgresql.conf && \
    chmod 644 /etc/postgresql/postgresql.conf

HEALTHCHECK --interval=5s --timeout=5s --retries=10 \
    CMD pg_isready -U postgres -d postgres